version: 0.2.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true

configuration: Release
platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

install:
- if not exist gtk-sharp-2.12.42.msi appveyor DownloadFile https://dl.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.42.msi
- msiexec /i gtk-sharp-2.12.42.msi /qn /norestart
- if not exist gtk-sharp-2.99.3.msi appveyor DownloadFile https://download.gnome.org/binaries/win32/gtk-sharp/2.99/gtk-sharp-2.99.3.msi
- msiexec /i gtk-sharp-2.99.3.msi /qn /norestart

cache:
- gtk-sharp-2.12.42.msi
- gtk-sharp-2.99.3.msi
- packages

nuget:
  project_feed: true
  disable_publish_on_pr: true

build_script:
- nuget restore
- msbuild Xwt\Xwt.csproj /target:Build /property:Configuration=Release;Platform=AnyCPU /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- msbuild Xwt.Gtk\Xwt.Gtk.csproj /target:Build /property:Configuration=Release;Platform=AnyCPU /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- msbuild Xwt.Gtk.Windows\Xwt.Gtk.Windows.csproj /target:Build /property:Configuration=Release;Platform=AnyCPU /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- msbuild Xwt.Gtk.Mac\Xwt.Gtk.Mac.csproj /target:Build /property:Configuration=Release;Platform=AnyCPU /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- msbuild Xwt.Gtk\Xwt.Gtk3.csproj /target:Build /property:Configuration=Release;Platform=AnyCPU /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- msbuild Xwt.WPF\Xwt.WPF.csproj /target:Build /property:Configuration=Release;Platform=AnyCPU /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- msbuild Xwt.XamMac\Xwt.XamMac.csproj /target:Build /property:Configuration=Release;Platform=AnyCPU /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- mkdir nuget
- NuGet pack Xwt\Xwt.csproj -Properties "Configuration=Release;Platform=AnyCPU" -Symbols -OutputDirectory nuget
- NuGet pack Xwt.Gtk\Xwt.Gtk.csproj -Properties "Configuration=Release;Platform=AnyCPU" -Symbols -OutputDirectory nuget
- NuGet pack Xwt.Gtk.Windows\Xwt.Gtk.Windows.csproj -Properties "Configuration=Release;Platform=AnyCPU" -Symbols -OutputDirectory nuget
- NuGet pack Xwt.Gtk.Mac\Xwt.Gtk.Mac.csproj -Properties "Configuration=Release;Platform=AnyCPU" -Symbols -OutputDirectory nuget
- NuGet pack Xwt.Gtk\Xwt.Gtk3.csproj -Properties "Configuration=Release;Platform=AnyCPU" -Symbols -OutputDirectory nuget
- NuGet pack Xwt.WPF\Xwt.WPF.csproj -Properties "Configuration=Release;Platform=AnyCPU" -Symbols -OutputDirectory nuget
- NuGet pack Xwt.XamMac\Xwt.XamMac.csproj -Properties "Configuration=Release;Platform=AnyCPU" -Symbols -OutputDirectory nuget
- dir nuget

test_script:
- ps: >-
    msbuild Xwt.sln /p:Configuration="Win-Debug" /p:Platform="Any Cpu" /verbosity:quiet

    $wc = New-Object 'System.Net.WebClient'

    nunit-console-x86.exe --framework=4.0 -domain=None -noshadow -nothread Testing\CoreTests\bin\Debug\CoreTests.dll

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))

    nunit-console-x86.exe --framework=4.0 -domain=None -noshadow -nothread Testing\bin\WpfTestRunner.exe

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))

    $env:Path += ";C:\Program Files (x86)\GtkSharp\2.12\bin"

    $env:GTK_BASEPATH = "C:\Program Files (x86)\GtkSharp\2.12\"

    nunit-console-x86.exe --framework=4.0 -domain=None -noshadow -nothread Testing\bin\GtkTestRunner.exe

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))

artifacts:
- path: nuget\*.nupkg
  name: Xwt-$(APPVEYOR_BUILD_VERSION)
deploy:
- provider: NuGet
  api_key:
    secure: C0hKv2gXXCmE0YzVK8ZuY6o32lC6gYQqcNCPEoGyRki0lODQawgIgFnH0XgMjjX2
  skip_symbols: true
  on:
    branch: master
